name: Build Mantle Blockscout

on:
  workflow_dispatch:
    inputs: 
      ref: 
        required: true
      tag: 
        required: false

env:
  OTP_VERSION: '24.3.4.1'
  ELIXIR_VERSION: '1.13.4'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.inputs.ref }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          repository: mantlenetworkio/blockscout
          ref: ${{ github.event.inputs.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mantlenetworkio/mantle-blockscout

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          cache-from: type=registry,ref=mantlenetworkio/mantle-blockscout:buildcache
          cache-to: type=registry,ref=mantlenetworkio/mantle-blockscout:buildcache,mode=max
          tags: mantlenetworkio/mantle-blockscout:latest, mantlenetworkio/mantle-blockscout:${{ env.RELEASE_VERSION }}
          platforms: linux/arm64,linux/amd64
          build-args: |
            CACHE_EXCHANGE_RATES_PERIOD=
            DISABLE_READ_API=false
            API_PATH=/
            NETWORK_PATH=/
            DISABLE_WEBAPP=false
            DISABLE_WRITE_API=false
            CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
            WOBSERVER_ENABLED=false
            ADMIN_PANEL_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            SOCKET_ROOT=